[build]
  publish   = "html"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "DISCORD_WEBHOOK"
  SECRETS_SCAN_OMIT_PATHS = "html/Reports/Arrest-Report.html"
