[build]
  publish   = "html"
  functions = "netlify/functions"

[build.environment]
  # only scan these specific files; any others get skipped
  SECRETS_SCAN_OMIT_PATHS = "html/Reports/Arrest-Report.html"
